version: 2
updates:
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: weekly
    day: saturday
    time: '00:00'
    timezone: 'Asia/Tokyo'
  open-pull-requests-limit: 10
  reviewers:
    - sotalbireo
  assignees:
    - sotalbireo
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
